<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CreatorPlatform.Orders.Application\CreatorPlatform.Orders.Application.csproj" />
    <ProjectReference Include="..\CreatorPlatform.Orders.Domain\CreatorPlatform.Orders.Domain.csproj" />
    <ProjectReference Include="..\..\..\Shared\CreatorPlatform.Shared.Infrastructure\CreatorPlatform.Shared.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Payments\CreatorPlatform.Payments.Application\CreatorPlatform.Payments.Application.csproj" />
    <ProjectReference Include="..\..\Creators\CreatorPlatform.Creators.Domain\CreatorPlatform.Creators.Domain.csproj" />
    <ProjectReference Include="..\..\Products\CreatorPlatform.Products.Domain\CreatorPlatform.Products.Domain.csproj" />
    <ProjectReference Include="..\..\LandingPages\CreatorPlatform.LandingPages.Domain\CreatorPlatform.LandingPages.Domain.csproj" />
    <ProjectReference Include="..\..\Analytics\CreatorPlatform.Analytics.Domain\CreatorPlatform.Analytics.Domain.csproj" />
    <ProjectReference Include="..\..\Marketing\CreatorPlatform.Marketing.Domain\CreatorPlatform.Marketing.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.8" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
    <PackageReference Include="Stripe.net" Version="51.2.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
